spring:
  datasource:
    url: jdbc:mysql://124.222.142.222:3306/security_springboot?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: Server2008!
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    #REDIS 数据库索引（默认为0）
    database: 1
    #redis服务地址
    host: 124.222.142.222
    #redis服务连接端口
    port: 6379
    #redis密码（没有密码默认为空）
    password:
    #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        #连接超时时间（毫秒）
    timeout: 5000

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 9988